pipeline {
    agent any

    parameters {
        string defaultValue: 'main', name: 'BRANCH', trim: true
    }

    stages {
        stage('Git checkout') {
            steps {
                git branch: '${BRANCH}', url: 'https://github.com/ajjankowski/BDD-Selenium-Cucumber.git'
                echo "Repository checked on ${BRANCH} branch"
            }
        }
        stage('Run tests') {
            steps {
                echo 'Running tests stage'
                bat 'mvn clean test'
                echo 'Tests completed'
            }
        }
        stage('Build report') {
            steps {
                echo 'Building report'
                cucumber buildStatus: 'null', customCssFiles: '', customJsFiles: '', failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: '**/*.json', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
                echo "Report build"
            }
        }
    }
}
